[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "hugo v0.148.2+extended+withdeploy linux/amd64 BuildDate=unknown"
